### ISSUE TITLE
Is the code for LongLLMLingua out?

### ISSUE THREAD

**Issue by darinkishore** [microsoft/LLMLingua#12]
When I look through 2 of the example, it seems like regular LLMLingua is being used. Is LongLLMLingua out yet? I only see the readme paper updates.

Sorry if I've missed anything obvious!

**Comment by iofu728** [comment]
Hi @darinkishore, thank you for your interest in our project.   
  
Indeed, you can use **LongLLMLingua** by setting the `rank_method` to `longllmlingua`. Here's how you can do it:  
   
```python  
prompt  = compressor.compress_prompt(  
    context=documents,  
    instruction=instruction,  
    question=question,  
    ratio=0.75, # for 4x speedup  
    iterative_size=200,  
    condition_compare=True,  
    condition_in_question='after_condition',  
    rank_method='longllmlingua',  
    reorder_context='sort',  
    dynamic_context_compression_ratio=0.3,  
    context_budget="+200",  
)  
```  
Most of our examples use LongLLMLingua, including those for [**RAG**](https://github.com/microsoft/LLMLingua/blob/main/examples/RAG.ipynb), [**Online Meetings**](https://github.com/microsoft/LLMLingua/blob/main/examples/OnlineMeeting.ipynb), [**Code**](https://github.com/microsoft/LLMLingua/blob/main/examples/Code.ipynb), and [RAG using LlamaIndex](https://github.com/microsoft/LLMLingua/blob/main/examples/RAGLlamaIndex.ipynb).

**Comment by darinkishore** [comment]
Thank you so much! If this could be highlighted in the docs would probably prevent similar queries in the future. And yeah, your paper is really really exciting!

**Comment by iofu728** [comment]
Thanks for your suggestion, we'll polish the READM soon.
