### ISSUE TITLE
[Feature Request]:  Docker service support

### ISSUE THREAD

**Issue by eav-solution** [microsoft/LLMLingua#132]
### Additional context

Hello author,
Could you please consider add docker service support ?

**Comment by iofu728** [comment]
Hi @eav-solution, thanks for your advice.

However, LLMLingua is a very lightweight pip package. If you need to use it, you can simply install it using `pip install llmlingua`. No additional environment dependencies are required.

If you encounter any issues with the installation, please provide the relevant context, and we can help you resolve them.
