### ISSUE TITLE
Experiments[Question]: 

### ISSUE THREAD

**Issue by 520zw** [microsoft/LLMLingua#164]
### Describe the issue

what is 1-shot / half-shot /quarter-shot constraint in experiments

**Comment by iofu728** [comment]
Hi @520zw, sorry for the late response.

In Table 2, the "1/half/quarter-shot constraint" refers to few-shot learning tasks, meaning the target compression ratio is equal to the original token size / the token size of a 1-shot demonstration, and so on.

**Comment by 520zw** [comment]
Thanks for the reply, does the one-shot demonstration mean that Cot only contains one reference example?is there a requirement to select this reference example?

**Comment by 21-10-4** [comment]
what is 1-shot / half-shot /quarter-shot constraint in experiments？
我还是无法理解。1-shot constraint代表the original token（包含一个示例） ，half-shot constraint指什么，半个示例？
