### ISSUE TITLE
[Question]: QA evaluation on chat (instruct) models

### ISSUE THREAD

**Issue by cornzz** [microsoft/LLMLingua#188]
### Describe the issue

In the provided `metrics.py` script the default behavior of the QA evaluation function `evaluate_with_gt` is to truncate the prediction at the first newline `\n` character. However, instruct models sometimes preface their answer with an introductory sentence and some newlines, followed by the correct answer, for example:

```json
        "questions": [
            "What campaign is mentioned in the transcript?"
        ],
        "answers": [
            "Back From the Brink.",
        ],
        "model_answers": [
            "The campaigns mentioned in the transcript are:\n\n1. Back From the Brink\n2. The International Campaign to Abolish Nuclear Weapons",
        ]
```

In such cases the correct answer is truncated away, which seemingly affects the overall QA score of an instruct model by 1-2 points (vs. no truncation). Should I not truncate the model answers when using instruct models?

**Comment by iofu728** [comment]
Hi @cornzz, we followed the evaluation metrics from LongBench for this section https://github.com/THUDM/LongBench/blob/main/metrics.py. If the LLM's generation results do not align with this logic, feel free to modify it based on your specific case.
