### ISSUE TITLE
[BUG] Code That Seems Pointless

### ISSUE THREAD

**Issue by ryan-minato** [microsoft/LLMLingua#189]
This code seems to always means `- 0` , making the code look pointless.

or is there something I'm overlooking?"

https://github.com/microsoft/LLMLingua/blob/2dbdbd37aef3b4346c2feec0ff8fba7dc3d42171/llmlingua/prompt_compressor.py#L2039

**Comment by iofu728** [comment]
Hi @ryan-minato, this logic was used during our experiments but was not adopted in the final version, so it has been set to 0. Please feel free to disregard it.
