### ISSUE TITLE
[Question]: Reproduction of Big Bench Hard with LLMLingua-2

### ISSUE THREAD

**Issue by cornzz** [microsoft/LLMLingua#191]
### Describe the issue

As there is no example for compression of BBH prompts given in the experiments folder I wanted to ask, which parameters were used for the compression of [the CoT prompts](https://github.com/suzgunmirac/BIG-Bench-Hard/tree/main/cot-prompts) used for big bench hard? Specifically, which values for the params

2. `compression_rate` / `target_token`
3. `force_tokens`
4. `force_reserve_digit`

were used, and was `use_context_level_filter` set to true? 
Furthermore, there are 3 CoT example prompts for each task, how was the compression done, were they passed as a single string or as a list, with each CoT prompt as a separate item, as done for the GSM8K CoT prompts [here](https://github.com/microsoft/LLMLingua/blob/main/experiments/llmlingua2/evaluation/scripts/compress.sh#L19)?

**Comment by iofu728** [comment]
Hi @pzs19, could you help to answer this question?

**Comment by cornzz** [comment]
Thank you!

**Comment by cornzz** [comment]
@pzs19 Sorry, I do have a follow-up question regarding your response:

>     1. "target_token" is described in "Tokens" column of the Table 3 in our [paper](https://aclanthology.org/2024.findings-acl.57.pdf).

I was of the impression that the column "Tokens" was the actual achieved token count, not the `target_token` parameter? Otherwise it should be the same value for 1-shot constraint and half-shot constraint, respectively, but in reality its a different value for each compression method?

**Comment by pzs19** [comment]
The meaning of "1-/half-shot constraint" is [here](https://github.com/microsoft/LLMLingua/issues/185#issuecomment-2429179097)

**Comment by cornzz** [comment]
Thank you!
