### ISSUE TITLE
Can you provide the NaturalQuestions test dataset?

### ISSUE THREAD

**Issue by czwlines** [microsoft/LLMLingua#5]
The LongLLMLingua evaluate performance on "NaturalQuestions", but I cannot find any source to download it, can you provide this test dataset?

(I try to communicate the author of "Lost in Middle", but I haven't received a reply yet.)

**Comment by iofu728** [comment]
Hi @czwlines, you can find the dataset in [their repo](https://github.com/nelson-liu/lost-in-the-middle/tree/main/qa_data).

**Comment by czwlines** [comment]
> Hi @czwlines, you can find the dataset in [their repo](https://github.com/nelson-liu/lost-in-the-middle/tree/main/qa_data).

thanks!!!
