### ISSUE TITLE
[BUG] ratio computation results in `ZeroDivisionError: division by zero` with `compressed_tokens=0`

### ISSUE THREAD

**Issue by davidberenstein1957** [microsoft/LLMLingua#53]
https://github.com/microsoft/LLMLingua/blob/f9304a992e0c65b669825f64bca3db76dbb78e9a/llmlingua/prompt_compressor.py#L285

**Comment by iofu728** [comment]
Hi @davidberenstein1957, thank you for your assistance. I have merged this PR.
