### ISSUE TITLE
Out of Memory error with llm_lingua

### ISSUE THREAD

**Issue by ankitpdc** [microsoft/LLMLingua#6]
Using the following code

llm_lingua = PromptCompressor(
        model_name = "meta-llama/Llama-2-7b-hf",
        device_map = "cuda:0",
        use_auth_token = False,
        open_api_config = {},
    )
compressed_prompt = llm_lingua.compress_prompt(prompt, instruction="", question=question, target_token=200)

However, I am getting an error, out of memory: 
![image](https://github.com/microsoft/LLMLingua/assets/51477387/0cedbe18-26f0-4e01-88c0-ed784d91df83)

Since, model is loading to only 1 partition of the GPU and not using all the 4. What changes should I do?

![image](https://github.com/microsoft/LLMLingua/assets/51477387/d64acef8-0dd0-4615-a7a7-5ec889a639c1)

**Comment by iofu728** [comment]
Hi @ankitpdc, to enable multi-GPU support, you can set the `device_map` parameter to `"balanced"` like this:  
   
```python  
llm_lingua = PromptCompressor(device_map="balanced")  
```  
   
For more details, please refer to the [documentation](https://github.com/microsoft/LLMLingua/blob/main/DOCUMENT.md#initialization).

**Comment by ankitpdc** [comment]
device_map = "balanced" or "auto" loading the data to CPU only not GPU.
Resolved the issue by adding the argument while creating model instance using AutoModelForCausalLM : device_map='auto'
instead of using .to(device) for moving model to GPU

![image](https://github.com/microsoft/LLMLingua/assets/51477387/e56307a4-44c0-4662-9e9f-f3cee9054c2f)

**Comment by iofu728** [comment]
> device_map = "balanced" or "auto" loading the data to CPU only not GPU. Resolved the issue by adding the argument while creating model instance using AutoModelForCausalLM : device_map='auto' instead of using .to(device) for moving model to GPU
> 
> ![image](https://user-images.githubusercontent.com/51477387/276098851-e56307a4-44c0-4662-9e9f-f3cee9054c2f.png)

Hi @ankitpdc, that's not quite right. The 'auto' or 'balanced' options will follow the 'else' logic in https://github.com/microsoft/LLMLingua/blob/main/llmlingua/prompt_compressor.py#L50C13-L60, and the default device for data is 'cuda' https://github.com/microsoft/LLMLingua/blob/main/llmlingua/prompt_compressor.py#L38-L40.
