### ISSUE TITLE
Why no integration with Langchain till now? 

### ISSUE THREAD

**Issue by AIAnytime** [microsoft/LLMLingua#71]
I can see there is no docs available for community to use LLMLingua with Langchain. We have with Llama Index but not langchain. Is there any example how one can use this in Langchain for RAG use cases?

**Comment by iofu728** [comment]
Hi @AIAnytime,

Currently, we do not have an official implementation of LLMLingua for Langchain. If you are willing to contribute your implementation, I would be delighted to feature it on our homepage. Details regarding the implementation can be found in #31. Thank you once again for your support.

**Comment by iofu728** [comment]
Thanks to @thehapyone's contribution, LLMLingua is now available in Langchain. You can follow this notebook for guidance.

**Comment by AIAnytime** [comment]
> Thanks to @thehapyone's contribution, LLMLingua is now available in Langchain. You can follow this notebook for guidance.

Which notebook?

**Comment by couturierc** [comment]
> Which notebook?

https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/retrievers/llmlingua.ipynb

**Comment by AIAnytime** [comment]
I can confirm this is not working with Langchain and it gives below error:

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-44-b268e5b787ea>](https://localhost:8080/#) in <cell line: 2>()
      1 from langchain.retrievers import ContextualCompressionRetriever
----> 2 from langchain_community.retrievers.document_compressors import LLMLinguaCompressor
      3 from langchain_openai import ChatOpenAI

ModuleNotFoundError: No module named 'langchain_community.retrievers.document_compressors'`

**Comment by AIAnytime** [comment]
> > Which notebook?
> 
> https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/retrievers/llmlingua.ipynb

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-44-b268e5b787ea>](https://localhost:8080/#) in <cell line: 2>()
      1 from langchain.retrievers import ContextualCompressionRetriever
----> 2 from langchain_community.retrievers.document_compressors import LLMLinguaCompressor
      3 from langchain_openai import ChatOpenAI

ModuleNotFoundError: No module named 'langchain_community.retrievers.document_compressors'`

I double checked that I have installed it but it gives the error.

**Comment by thehapyone** [comment]
You have to wait for the langchain team to release a new version of the community package - https://github.com/langchain-ai/langchain/releases

**Comment by mmilannaik** [comment]
Is the issue got fixed for langchain? I can see there is a new release of langchain two days ago

**Comment by mmilannaik** [comment]
> You have to wait for the langchain team to release a new version of the community package - https://github.com/langchain-ai/langchain/releases

Is the issue got fixed for langchain? I can see there is a new release of langchain two days ago
