### ISSUE TITLE
Out of Memory Error with Llama-2-7b

### ISSUE THREAD

**Issue by ankitpdc** [microsoft/LLMLingua#8]
I am using following command to test it:

from llmlingua import PromptCompressor

llm_lingua = PromptCompressor(
        model_name = "NousResearch/Llama-2-7b-hf",
        device_map = "cuda:0",
        use_auth_token = False,
        open_api_config = {},
    )
compressed_prompt = llm_lingua.compress_prompt(prompt, instruction="", question="some question", target_token=200)

However it is giving me out of memory error:
![Screenshot from 2023-10-17 16-09-39](https://github.com/microsoft/LLMLingua/assets/51477387/f2a92e4c-1bc3-40a5-a990-b6e55e3745a0)

Probably reason is, model is getting loaded to only 1 partition and not all the partitions. Llama-2-7b-hf otherwise runs perfectly in the machine. It is just not working with this library. What changes would you suggest?
![Screenshot from 2023-10-17 16-07-30](https://github.com/microsoft/LLMLingua/assets/51477387/e156049c-2dc8-486b-af36-96c687dd4c64)

**Comment by ankitpdc** [comment]
Received a response: PromptCompressor(device_map="balanced")

**Comment by ankitpdc** [comment]
Received a response: PromptCompressor(device_map="balanced")

**Comment by vxld100** [comment]
What got it working for you? I have the same issue.

**Comment by yellowishee** [comment]
same issue

**Comment by Avkashhirpara** [comment]
same issue here, can someone please update info on the tread why it is closed and what was the exact solution.
