### ISSUE TITLE
Index error for small token amounts

### ISSUE THREAD

**Issue by oz03-hub** [microsoft/LLMLingua#84]
Hello again, I noticed a strange behavior while developing using llmlingua, for small prompts such as "hello" or "who", compress function throws an error for index 0 out of range. 

`    """
    Token compression using llmlingua that uses gpt-2 small llm.
    """

    llm_lingua = PromptCompressor(model_name=optimizer_model, device_map=device_map)

    try:
        print(user_prompt)
        print("Compressing")
        compressed_prompt = llm_lingua.compress_prompt(
            context=[user_prompt],
            ratio=0.2,
        )
`

here is initialization to trigger error, thanks and I am looking forward to updates

**Comment by oz03-hub** [comment]
Same behavior also happens in hugging face demo as well

**Comment by iofu728** [comment]
Thank you for pointing this out. we will fix the issue ASAP.

**Comment by iofu728** [comment]
Fixed in #87
